sudo: false # Run on containers rather than VMs to enable caching
cache:
  directories:
  - $HOME/.gradle
  - .gradle
env:
  global:
  - USER=ApiSecRay
    # BINTRAY API KEY:
  - secure: XgXG6UVWg8+MpXXaNH0c3w3Tsp9XBi1eXPbGUi16ztZUS/DVDnCbrFFX1ABXz4Dw+qCER67hjtcL6O0bczt1oJFFurC1tMzSXqZSrVIDcDAEVKCi08dy73yxm0QX4HFWg/z67O0DzJi8teYMcItSgBAsKbhnVEV+mnYxS/wR86c=
    # COVERITY API KEY:
  - secure: "Rtj2gG4t84+r62T4IXOsJPA+3R8cfFJaCrehh8W9gFGXTRvwEnpBLkjJGBT//DhpnENZFncjy7Kk5LdDY3dY4qBtek+lxrAXTWqHmxOAEuwHBymlSWsQt0II1LD8HmmHeMUvo2LPq6flbZG7x4qR6/bk2y5BFAtdLn8G3G/CbOg="
    # HIPCHAT API KEY:
  - secure: "UN6AK7fRKtaR50eo6IMCTeAgBkQUiCXu1PizMyHqwMesPGWIcuTZ1mSse65+lua6bfk9nabKVj/fTfP+1/mYPUZk+ltQJnoEGGfR+SB/8EzH6
WesK3eGbG8jWz+Lm2tVFBhppZ+DMpUzDtcv5I+S1/fg0T8PT6ckvejBzDmqqXw="

language: java
jdk:
- openjdk7
install: true
script: ./gradlew build


## Notifications
notifications:
  slack:
    secure: LJfuvagJjFqaoA8AJQtfLOtymOzpifA2qUqA1XI5Kd67sVFY5BViIHZ/+qy3jV+Ve7Msl8St+XiB9zrLqKOxFNNaFvYZYgpn4fb4RDxVWipZrVY9/DRwEImzuWNsx1Il7rn9zWK0jgmIyK2DK6wtWPnZUTinHGPIw3RtvR22AyA=
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9964f490aeaa2be3c3c9
    on_success: always
    on_failure: always
    on_start: true
  hipchat: $HIPCHAT_KEY@Radl

after_success:
  - ./deploy_to_bintray.sh
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
- gem install mime-types -v 2.6.2

deploy:
  provider: releases
  api_key:
    secure: RWpPmmzrJ2Ddx8nwG6k6UZm98o7gMRpGJ2liCFUGy5Uuf8w5AXj6xMLKFdcK3pZFSYBQ1+4DycFPAXmFCfP+nv6dX9PbDkOVB669ecnxStfVse0zXYgjuNEmhAht6wDb/O6jiNUrnyXcmQDExhXC3SigtnWcLUiRbJOYGoc3oSQ=
  file_glob: true
  file:
  - java/core/build/libs/*
  - java/eclipse/build/libs/*
  - java/gradle/build/libs/*
  - java/maven/build/libs/*
  on:
    repo: restful-api-description-language/RADL
    tags: true
    all_branches: true
    
addons:
  coverity_scan:
    project:
      name: "restful-api-description-language/RADL"
      description: "Build submitted via Travis CI"
    notification_email: rssinnema@yahoo.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew assemble"
    branch_pattern: coverity_scan
