/*
 * Copyright (c) EMC Corporation. All rights reserved.
 */

package radl.maven;

/**
 * Maven plugin configuration parameters
 */
public interface MavenConfig {

  String RADL_DIR_NAME = "radlDirName";
  String RADL_DIR_NAME_DEFAULT = "${project.basedir}/src/main/radl";

  String DOCS_DIR = "docsDir";
  String DOCS_DIR_DEFAULT = "${project.build.directory}/radl";

  String ISSUE_FILE = "issueFile";
  String ISSUE_FILE_DEFAULT = DOCS_DIR_DEFAULT + "/radl-issues.xml";

  String BASE_DIR = "baseDir";
  String BASE_DIR_DEFAULT = "${project.basedir}";

  String PACKAGE_PREFIX = "packagePrefix";
  String PACKAGE_PREFIX_DEFAULT = "radl.sample.rest.server";

  String FAIL_ON_VALIDATION_ERRORS = "failOnValidationErrors";
  String FAIL_ON_VALIDATION_ERRORS_DEFAULT = "true";

  String SRC_SET_DIR = "srcDir";
  String SRC_SET_DIR_DEFAULT = "${project.basedir}/src/main/java";

  String REL_GEN_SRC_DIR = "relativeGeneratedSourceDir";
  String REL_GEN_SRC_DIR_DEFAULT = "${project.build.directory}/generated-src/java";

  String REL_GEN_MAN_SRC_DIR = "relativeGeneratedManualSourceDir";
  String REL_GEN_MAN_SRC_DIR_DEFAULT = "${project.build.directory}/generated-src/manual";

  String SERVICE_NAME = "serviceName";
  String SERVICE_NAME_DEFAULT = "${project.name}";

  String SCM = "scm";
  String SCM_DEFAULT = "default";

  String CLASSPATH_SCOPE = "classpathScope";
  String CLASSPATH_SCOPE_DEFAULT = "runtime";

  String EX_CLASSPATH = "extraClasspath";
  String EX_CLASSPATH_DEFAULT = "";

  String EX_PROCESSORS = "extraProcessors";
  String EX_PROCESSORS_DEFAULT = "";

  String HEADER = "header";
  String HEADER_DEFAULT = "Generated by RADL";

  String KEEP_ARGS_FILE = "keepArgumentsFile";
  String KEEP_ARGS_FILE_DEFAULT = "false";

  String PRE_EXTRACT = "preExtract";
  String PRE_EXTRACT_DEFAULT = "false";

  String RADL_CORE_VERSION = "radlCoreVersion";
  String RADL_CORE_VERSION_DEFAULT = "";

  String SKIP_CLASSPATH = "skipClasspath";
  String SKIP_CLASSPATH_DEFAULT = "false";
}
